[package]
name = "canvas"
version = "0.1.0"
authors = ["Dan <dan@yellowiki.xyz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.0.2", features = ["full"] }
reqwest = { version = "0.10.10", features = ["json"] }
serde = { version = "1.0.116", features = ["derive"] }
serde_json = "1.0.61"
lazy_static = "1.4.0"
backoff = { version = "0.2.1", features = ["tokio"] }
futures = "0.3.8"
async-trait = "0.1.40"
chrono = { version = "0.4.19", features = ["serde"] }
colored = "2.0.0"
structopt = "0.3.21"
dirs = "3.0.1"
toml = "0.5.8"
color-eyre = "0.5.6"
