[package]
name = "canvas"
version = "0.1.0"
authors = ["Dan <dan@yellowiki.xyz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "0.2.22", features = ["full"] }
reqwest = { version = "0.10.8", features = ["json"] }
anyhow = "1.0.33"
serde = { version = "1.0.116", features = ["derive"] }
serde_json = "1.0.57"
lazy_static = "1.4.0"
backoff = { version = "0.2.1", features = ["tokio"] }
futures = "0.3.5"
async-trait = "0.1.40"
chrono = { version = "0.4.15", features = ["serde"] }
colored = "2.0.0"
structopt = "0.3.17"
dirs = "3.0.1"
toml = "0.5.6"
