[package]
name = "canvas"
version = "0.1.0"
authors = ["Dan <dan@yellowiki.xyz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.20.1", features = ["full"] }
reqwest = { version = "0.11.11", features = ["json"] }
serde = { version = "1.0.143", features = ["derive"] }
serde_json = "1.0.83"
lazy_static = "1.4.0"
backoff = { version = "0.2.1", features = ["tokio"] }
futures = "0.3.23"
async-trait = "0.1.57"
chrono = { version = "0.4.22", features = ["serde"] }
colored = "2.0.0"
structopt = "0.3.26"
dirs = "4.0.0"
toml = "0.5.9"
color-eyre = "0.6.2"
toml_edit = "0.2.1"
indicatif = "0.15.0"
generational-arena = "0.2"
serde_path_to_error = "0.1.8"
