[package]
name = "canvas"
version = "0.1.0"
authors = ["Dan <dan@yellowiki.xyz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.13.0", features = ["full"] }
reqwest = { version = "0.11.6", features = ["json"] }
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.68"
lazy_static = "1.4.0"
backoff = { version = "0.2.1", features = ["tokio"] }
futures = "0.3.17"
async-trait = "0.1.51"
chrono = { version = "0.4.19", features = ["serde"] }
colored = "2.0.0"
structopt = "0.3.25"
dirs = "4.0.0"
toml = "0.5.8"
color-eyre = "0.5.11"
toml_edit = "0.2.1"
indicatif = "0.15.0"
generational-arena = "0.2"
serde_path_to_error = "0.1.5"
